# Generated by Django 4.1.7 on 2023-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_new_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=50)),
                ('suite', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default=0, max_length=50)),
                ('lat', models.CharField(default='', max_length=50)),
                ('lng', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('catchpharse', models.CharField(default='', max_length=100)),
                ('bs', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
